### ISSUE TITLE
MythicMob Integration 

### ISSUE THREAD

**Issue by BobtheBob123456** [CodeDoctorDE/ItemMods#37]
### Is your feature request related to a problem? Please describe

No

### Describe your feature request!

There is a plugin called Mythicmobs that allows you to  create custom mobs, and what equipment they have. You can even create custom items.

How it would work is you would go into MythicMobs items and under NBT put the name of one of the items you created.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hello,

I have currently no time to add new integrations.
Another aspect is that I'm not very excited to develop integrations for closed source plugins
